### ISSUE TITLE
C3C FBState Utility is now C3C UFC Utility

### ISSUE THREAD

**Issue by BadAimWeeb** [c3cbot/c3c-fbstate#21]
To comply with Facebook (Meta Inc) request regarding the use of "FB" trademark on the name of the extension, "C3C FBState Utility" is now "C3C UFC Utility". Following with that, all mentions of "FBState" going forward should be called "UFC" (UFC file, UFC data).

The UFC format may (or may not) be used for other platforms other than Facebook. If used, "UFC" name can still be used with clarification if necessary.

This extension's functionality will not change because of this name change.

**Comment by chappy-ai4** [comment]
To comply with Facebook (Meta Inc) request regarding the use of "FB" trademark on the name of the extension, "C3C FBState Utility" is now "C3C UFC Utility". Following with that, all mentions of "FBState" going forward should be called "UFC" (UFC file, UFC data).

The UFC format may (or may not) be used for other platforms other than Facebook. If used, "UFC" name can still be used with clarification if necessary.

This extension's functionality will not change because of this name change.
